# Generated by Django 4.2.6 on 2023-11-18 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('model', models.CharField(max_length=255, verbose_name='модель')),
                ('photo', models.ImageField(blank=True, upload_to='home/img/%Y/%m/%d/', verbose_name='Главное фото')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описаниеписание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('num_top', models.IntegerField(default=0, verbose_name='Номер в топе')),
                ('is_availability', models.BooleanField(default=True, verbose_name='В наличии')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('extended_description', models.TextField(blank=True, null=True, verbose_name='подробное описание')),
                ('characteristics', models.TextField(blank=True, null=True, verbose_name='характеристики')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='author_create_product', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('author_last_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_update_product', to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.category_product', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['time_create', 'model'],
            },
        ),
    ]
