# Generated by Django 4.2.6 on 2023-11-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Краткое описаниеписание'),
        ),
    ]
