# Generated by Django 4.2.6 on 2023-11-25 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория услуги',
                'verbose_name_plural': 'Категории услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('photo', models.ImageField(blank=True, upload_to='service/img/%Y/%m/%d/', verbose_name='Главное фото')),
                ('short_description', models.TextField(blank=True, max_length=255, verbose_name='Краткое описаниеписание')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('num_top', models.IntegerField(default=0, verbose_name='Номер в топе')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('extended_description', models.TextField(blank=True, null=True, verbose_name='подробное описание')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='author_create_service', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('author_last_update', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_update_service', to=settings.AUTH_USER_MODEL, verbose_name='Автор изменения')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.category_service', verbose_name='Категория услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['time_create', 'name', 'price'],
            },
        ),
    ]
